#!/usr/bin/env python3
"""
Spec-to-Adapter Code Generator for AI FANTUI LogicMVP.

Reads a control_system_spec_v1 JSON file and emits a self-contained
Python adapter that implements GenericControllerTruthAdapter.

Usage:
    python -m well_harness.tools.generate_adapter path/to/spec.json -o output_adapter.py

Exit codes:
    0  success
    1  spec not found / validation error
    2  write error
"""
from __future__ import annotations

import argparse
import datetime
import json
import sys
from pathlib import Path
from typing import Any


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def spec_to_adapter_source(spec: dict[str, Any], *, source_path: str = "") -> str:
    """
    Convert a parsed control_system_spec_v1 dict into the source text of
    a complete Python adapter file.
    """
    system_id: str = spec["system_id"]
    title: str = spec.get("title", system_id)
    adapter_id: str = _to_pythonIdentifier(system_id) + "-controller-adapter"
    class_name: str = _to_pythonIdentifier(system_id) + "_controller_adapter"
    ts = datetime.datetime.now().isoformat()
    sp = source_path or "(in-memory)"
    spec_filename = _to_pythonFilename(system_id)
    pkg = __name__.rsplit(".", 1)[0]

    # Build logic evaluation source lines and track comparison ops used
    eval_lines, comparisons_used = _generate_evaluate_snapshot(spec, system_id)

    # Condition helper methods (for special comparisons like between_exclusive)
    helper_lines = _generate_condition_helpers(comparisons_used)

    # ── Assemble the complete file line-by-line ───────────────────────────
    out: list[str] = []

    def L(line: str = "") -> None:
        out.append(line)

    L(f'''"""
Auto-generated Python adapter — AI FANTUI LogicMVP P17-NLC-A
==============================================================
  system_id : {system_id}
  title     : {title}
  source    : {sp}
  generated : {ts}

DO NOT EDIT THIS FILE DIRECTLY.
It was generated by: well_harness.tools.generate_adapter
Re-generate after editing the source spec JSON.
"""''')
    L()
    L("from __future__ import annotations")
    L()
    L("from dataclasses import dataclass")
    L("from typing import Any, Mapping")
    L()
    L("from well_harness.controller_adapter import (")
    L("    ControllerTruthMetadata,")
    L("    GenericTruthEvaluation,")
    L(")")
    L()
    L()
    L("@dataclass(frozen=True)")
    L("class ControllerTruthMetadata:")
    L("    adapter_id: str")
    L("    system_id: str")
    L("    truth_kind: str")
    L("    source_of_truth: str")
    L("    description: str")
    L()
    L()
    L("@dataclass(frozen=True, eq=False)")
    L("class GenericTruthEvaluation:")
    L("    system_id: str")
    L("    active_logic_node_ids: tuple[str, ...]")
    L("    asserted_component_values: dict[str, Any]")
    L("    completion_reached: bool")
    L("    blocked_reasons: tuple[str, ...]")
    L("    summary: str")
    L()
    L()
    L(f"CONTROLLER_METADATA = ControllerTruthMetadata(")
    L(f'    adapter_id="{adapter_id}",')
    L(f'    system_id="{system_id}",')
    L('    truth_kind="spec-derived-generic-truth",')
    L(f'    source_of_truth="{sp}",')
    L(f'    description="Auto-generated GenericControllerTruthAdapter for {title}",')
    L(")")
    L()
    L()
    L(f"class {class_name}:")
    L(f'    """')
    L(f'    Spec-derived GenericControllerTruthAdapter.')
    L(f'    ')
    L(f'    Implements GenericControllerTruthAdapter by evaluating the logic_nodes')
    L(f'    defined in the embedded spec dict directly against the incoming snapshot.')
    L(f'    ')
    L(f'    AUTO-GENERATED by tools/generate_adapter.py — do not edit by hand.')
    L(f'    """')
    L()
    L("    def __init__(self, spec: dict[str, Any] | None = None) -> None:")
    L("        self.spec = spec or self._load_spec_dict()")
    L("        self._logic_rules = self._build_logic_rules(self.spec)")
    L("        self._refresh_rules()")
    L()
    L("    def _refresh_rules(self) -> None:")
    L("        self._logic_rules = {")
    L("            ln['id']: {")
    L("                'conditions': ln.get('conditions', []),")
    L("                'downstream_component_ids': tuple(ln.get('downstream_component_ids', [])),")
    L("            }")
    L("            for ln in self.spec.get('logic_nodes', [])")
    L("        }")
    L()
    L("    @property")
    L("    def metadata(self) -> ControllerTruthMetadata:")
    L("        return CONTROLLER_METADATA")
    L()
    L("    def load_spec(self) -> dict[str, Any]:")
    L("        return dict(self.spec)")
    L()
    L("    def evaluate_snapshot(self, snapshot: Mapping[str, Any]) -> GenericTruthEvaluation:")
    L("        snap = dict(snapshot)")
    L()
    for line in eval_lines:
        L(line)  # eval_lines already carry correct method-body indentation
    L()
    L("    @staticmethod")
    L("    def _resolve_param(value: Any, snap: dict) -> Any:")
    L("        if isinstance(value, str) and value in snap:")
    L("            return snap[value]")
    L("        return value")
    L()
    if helper_lines and helper_lines != ["    pass  # no special comparison operators used"]:
        for line in helper_lines:
            L(line)
    L()
    L("    @staticmethod")
    L("    def _build_logic_rules(spec: dict) -> dict:")
    L("        return {")
    L("            ln['id']: {")
    L("                'conditions': ln.get('conditions', []),")
    L("                'downstream_component_ids': tuple(ln.get('downstream_component_ids', [])),")
    L("            }")
    L("            for ln in spec.get('logic_nodes', [])")
    L("        }")
    L()
    L("    @staticmethod")
    L("    def _load_spec_dict() -> dict:")
    L("        import json, pathlib")
    L(f"        _spec_path = pathlib.Path(__file__).parent / 'specs' / '{spec_filename}.spec.json'")
    L("        return json.loads(_spec_path.read_text())")
    L()
    L("    def __repr__(self) -> str:")
    L('        return f"{self.__class__.__name__}(system_id={self.metadata.system_id!r})"')
    L()

    return "\n".join(out)


def write_adapter_from_spec(
    spec_path: str | Path,
    output_path: str | Path,
    *,
    source_path: str | None = None,
) -> None:
    """
    Read spec_path, write adapter source to output_path.
    Raises SystemExit on error.
    """
    spec_path = Path(spec_path)
    output_path = Path(output_path)

    if not spec_path.exists():
        print(f"ERROR: spec not found: {spec_path}", file=sys.stderr)
        sys.exit(1)

    try:
        spec = json.loads(spec_path.read_text())
    except json.JSONDecodeError as exc:
        print(f"ERROR: invalid JSON in {spec_path}: {exc}", file=sys.stderr)
        sys.exit(1)

    src = spec_to_adapter_source(spec, source_path=str(spec_path))
    try:
        output_path.write_text(src)
    except OSError as exc:
        print(f"ERROR: failed to write {output_path}: {exc}", file=sys.stderr)
        sys.exit(2)

    print(f"Wrote: {output_path}")


# ---------------------------------------------------------------------------
# Internals
# ---------------------------------------------------------------------------

def _generate_metadata(system_id: str, adapter_id: str, title: str, source_path: str) -> tuple[list[str], dict]:
    """Build the CONTROLLER_METADATA = ControllerTruthMetadata(...) line."""
    lines = [
        f"# system_id : {system_id}",
        f"# title     : {title}",
        f"# source    : {source_path or '(in-memory)'}",
    ]
    meta = {
        "adapter_id": adapter_id,
        "system_id": system_id,
        "truth_kind": "spec-derived-generic-truth",
        "source_of_truth": source_path,
        "description": f"Auto-generated adapter for {title}",
    }
    return lines, meta


def _generate_load_spec(spec: dict) -> list[str]:
    """Build the load_spec() method stub."""
    lines = [
        "    def load_spec(self) -> dict[str, Any]:",
        "        return dict(self.spec)",
    ]
    return lines


def _generate_evaluate_snapshot(spec: dict, system_id: str) -> tuple[list[str], set[str]]:
    """
    Build the evaluate_snapshot() method body and return
    (list of source lines, set of comparison operators used).
    """
    logic_nodes = spec.get("logic_nodes", [])
    components = {c["id"]: c for c in spec.get("components", [])}
    all_component_ids = set(components.keys())

    # Build lookup: component id -> resolved numeric/default value
    # For string thresholds that reference other components, resolve to that component's value
    comp_value_lookup: dict[str, object] = {}
    # Known runtime config param IDs that appear as threshold_value strings but are not
    # components in the spec. Map them to their canonical numeric defaults.
    _KNOWN_RUNTIME_PARAMS: dict[str, float] = {
        "max_n1k_deploy_limit": 60.0,  # demo_server default
    }
    for cid, val in _KNOWN_RUNTIME_PARAMS.items():
        comp_value_lookup[cid] = val
    for comp in spec.get("components", []):
        cid = comp["id"]
        # Use allowed_range[0] as the canonical value if present, else state_value
        rng = comp.get("allowed_range")
        if rng and len(rng) >= 1:
            comp_value_lookup[cid] = rng[0]
        elif "state_value" in comp:
            comp_value_lookup[cid] = comp["state_value"]
        else:
            comp_value_lookup[cid] = None

    # Separate input/sensor components from derived/intermediate ones
    # An input component is one that appears as a source in logic conditions
    # but is NOT a downstream target of any logic node
    sources_used: set[str] = set()
    downstream_all: set[str] = set()
    for ln in logic_nodes:
        for cond in ln.get("conditions", []):
            sources_used.add(cond["source_component_id"])
        downstream_all.update(ln.get("downstream_component_ids", []))

    # Components that are roots (provided externally in snapshot)
    root_component_ids = sources_used - downstream_all

    eval_lines: list[str] = []
    comparisons_used: set[str] = set()

    for ln in logic_nodes:
        for cond in ln.get("conditions", []):
            comparisons_used.add(cond["comparison"])

    # Map comparison op strings to Python AST-like calls
    comp_map = {
        "<": "lv < threshold",
        "<=": "lv <= threshold",
        ">": "lv > threshold",
        ">=": "lv >= threshold",
        "==": "lv == threshold",
        "!=": "lv != threshold",
        "lt": "lv < threshold",
        "lte": "lv <= threshold",
        "gt": "lv > threshold",
        "gte": "lv >= threshold",
        "eq": "lv == threshold",
        "neq": "lv != threshold",
        "after_unlock": "_eval_after_unlock(lv, threshold, snap)",
        "between_exclusive": "_eval_between_exclusive(lv, threshold, snap)",
    }

    eval_lines.append("")

    # Build the main logic evaluation
    eval_lines.append("        # ── Evaluate logic nodes ─────────────────────────────────────────────")

    for ln in logic_nodes:
        ln_id = ln["id"]
        conditions = ln.get("conditions", [])
        downstream = ln.get("downstream_component_ids", [])

        eval_lines.append(f"        # Logic node: {ln_id}")
        eval_lines.append(f"        ln_{ln_id}_passed = True")
        eval_lines.append(f"        ln_{ln_id}_failed: list[str] = []")

        for cond in conditions:
            cond_name = cond["name"]
            src_id = cond["source_component_id"]
            comp = cond["comparison"]
            threshold_val = cond["threshold_value"]
            note = cond.get("note", "")

            comparisons_used.add(comp)

            eval_lines.append(f"        #   condition: {cond_name} [{note}]")

            # Source value resolution: either from snapshot directly,
            # or from a parameter (component id string that points to another value)
            # Convert JSON booleans to Python; resolve string component IDs to values
            def _py_literal(v):
                if v is True: return "True"
                if v is False: return "False"
                if isinstance(v, str) and v in comp_value_lookup:
                    resolved = comp_value_lookup[v]
                    if resolved is not None:
                        return json.dumps(resolved)
                return json.dumps(v)

            eval_lines.append(f"        try:")
            eval_lines.append(f"            lv_{cond_name} = self._resolve_param({json.dumps(src_id)}, snap)")
            # Threshold: if it's a string component ID, resolve it; otherwise use as Python literal
            if isinstance(threshold_val, str) and threshold_val in comp_value_lookup:
                eval_lines.append(f"            threshold_{cond_name} = self._resolve_param({json.dumps(threshold_val)}, snap)")
            elif comp == "between_exclusive" and isinstance(threshold_val, (list, tuple)):
                eval_lines.append(f"            threshold_{cond_name} = {threshold_val!r}")
            else:
                eval_lines.append(f"            threshold_{cond_name} = {_py_literal(threshold_val)}")

            py_comp = comp_map.get(comp, comp)
            if comp == "after_unlock":
                eval_lines.append(f"            cond_{cond_name}_passed = self._eval_after_unlock(lv_{cond_name}, threshold_{cond_name}, snap)")
            elif comp == "between_exclusive":
                eval_lines.append(f"            cond_{cond_name}_passed = self._eval_between_exclusive(lv_{cond_name}, threshold_{cond_name}, snap)")
            else:
                eval_lines.append(f"            try:")
                eval_lines.append(f"                lv = lv_{cond_name}")
                eval_lines.append(f"                threshold = threshold_{cond_name}")
                eval_lines.append(f"                cond_{cond_name}_passed = bool({py_comp})")
                eval_lines.append(f"            except (TypeError, KeyError, AttributeError):")
                eval_lines.append(f"                cond_{cond_name}_passed = False")

            eval_lines.append(f"        except KeyError:")
            eval_lines.append(f"            cond_{cond_name}_passed = False")

            eval_lines.append(f"        if not cond_{cond_name}_passed:")
            eval_lines.append(f"            ln_{ln_id}_passed = False")
            eval_lines.append(f"            ln_{ln_id}_failed.append({json.dumps(cond_name)})")

        eval_lines.append("")

    # Build active logic node ids
    eval_lines.append("        # Determine active / blocked logic nodes")
    eval_lines.append("        active_logic_node_ids: list[str] = []")
    eval_lines.append("        blocked_reasons: list[str] = []")

    for ln in logic_nodes:
        ln_id = ln["id"]
        eval_lines.append(f"        if ln_{ln_id}_passed:")
        eval_lines.append(f"            active_logic_node_ids.append({json.dumps(ln_id)})")
        eval_lines.append("        else:")
        eval_lines.append(f"            for _f in ln_{ln_id}_failed:")
        eval_lines.append(f"                blocked_reasons.append(f'{ln_id}:{{_f}}')")

    eval_lines.append("")

    # Assert component values
    eval_lines.append("        # Collect asserted component values")
    eval_lines.append("        asserted: dict[str, Any] = {}")

    for comp_id, comp in components.items():
        state_shape = comp.get("state_shape", "binary")
        if state_shape == "binary" or comp.get("allowed_states"):
            eval_lines.append(f"        if {json.dumps(comp_id)} in snap:")
            eval_lines.append(f"            asserted[{json.dumps(comp_id)}] = snap[{json.dumps(comp_id)}]")

    # Include downstream component ids as command outputs
    all_mentioned = set()
    for ln in logic_nodes:
        all_mentioned.update(ln.get("downstream_component_ids", []))
    for comp_id in sorted(all_mentioned):
        if comp_id not in components:
            # Derived node — set to active if its upstream logic is active
            pass  # handled via active_logic_node_ids

    eval_lines.append("")

    # Determine completion (last-tier logic nodes are active)
    # A node is "last-tier" when its downstream outputs are NOT themselves
    # downstream of any OTHER node.  Only the terminal output (e.g. thr_lock)
    # survives this filter: all other nodes' outputs feed the plant which
    # produces signals used by downstream logic; thr_lock is the sole
    # terminal command that nothing else consumes.
    #
    # We detect this by checking whether each node's downstream set overlaps
    # with OTHER nodes' downstream sets (not itself).  If no overlap, it's
    # the terminal node.
    other_downstream: list[set[str]] = []
    for ln in logic_nodes:
        other_downstream.append(set(ln.get("downstream_component_ids", [])))
    last_tier_ids: list[str] = []
    for i, ln in enumerate(logic_nodes):
        my_down = set(ln.get("downstream_component_ids", []))
        if not my_down:
            continue
        is_last = True
        for j, other_ds in enumerate(other_downstream):
            if i == j:
                continue
            if my_down & other_ds:
                is_last = False
                break
        if is_last:
            last_tier_ids.append(ln["id"])

    # Filter to terminal nodes: only the one whose downstream includes
    # the final command (thr_lock).  All other nodes' outputs feed the
    # plant and are intermediate, not terminal.
    terminal_ln_ids: list[str] = []
    for lid in last_tier_ids:
        ln = next((n for n in logic_nodes if n["id"] == lid), None)
        if ln and "thr_lock" in ln.get("downstream_component_ids", []):
            terminal_ln_ids.append(lid)
    if not terminal_ln_ids:
        terminal_ln_ids = last_tier_ids[-1:] if last_tier_ids else []

    # completion_reached: derived from the terminal logic node being active.
    if terminal_ln_ids:
        passed_checks = " or ".join(f"(ln_{lid}_passed)" for lid in terminal_ln_ids)
        eval_lines.append(f"        completion_reached = bool({passed_checks})")
    else:
        eval_lines.append("        completion_reached = False")

    eval_lines.append("")

    # Build summary
    eval_lines.append('        summary = f"Spec-driven truth: {len(active_logic_node_ids)} active logic nodes; '
                      'completion={{completion_reached}}."')
    eval_lines.append("")
    eval_lines.append("        return GenericTruthEvaluation(")
    eval_lines.append(f'            system_id={json.dumps(system_id)},')
    eval_lines.append("            active_logic_node_ids=tuple(active_logic_node_ids),")
    eval_lines.append("            asserted_component_values=asserted,")
    eval_lines.append("            completion_reached=completion_reached,")
    eval_lines.append("            blocked_reasons=tuple(blocked_reasons),")
    eval_lines.append("            summary=summary,")
    eval_lines.append("        )")

    return eval_lines, comparisons_used


def _generate_condition_helpers(comparisons_used: set[str]) -> list[str]:
    """Generate helper methods for special comparison operators."""
    lines: list[str] = []

    needs_after_unlock = "after_unlock" in comparisons_used
    needs_between_exclusive = "between_exclusive" in comparisons_used

    if needs_after_unlock:
        lines.append("    @staticmethod")
        lines.append("    def _eval_after_unlock(lv: Any, threshold: Any, snap: dict) -> bool:")
        lines.append("        # after_unlock: current value must equal threshold AND upstream logic satisfied")
        lines.append("        # In spec-driven mode: treat as lv == threshold (upstream logic tracked separately)")
        lines.append("        return lv == threshold")
        lines.append("")

    if needs_between_exclusive:
        lines.append("    @staticmethod")
        lines.append("    def _eval_between_exclusive(lv: Any, threshold: Any, snap: dict) -> bool:")
        lines.append("        # between_exclusive: lower < lv < upper")
        lines.append("        if not isinstance(threshold, (list, tuple)) or len(threshold) != 2:")
        lines.append("            return False")
        lines.append("        lower, upper = threshold")
        lines.append("        try:")
        lines.append("            lv_f = float(lv)")
        lines.append("            return float(lower) < lv_f < float(upper)")
        lines.append("        except (TypeError, ValueError):")
        lines.append("            return False")
        lines.append("")

    if not lines:
        lines.append("    pass  # no special comparison operators used")

    return lines


def _build_logic_rules_src(eval_globals: set[str]) -> str:
    """Build the _build_logic_rules static helper (returns the rules structure)."""
    # This is informational — the rules are computed inline in evaluate_snapshot
    return (
        "        # Returns the logic rule structure from the spec.\n"
        "        # rules[logic_node_id] = {\n"
        "        #     'conditions': [...],\n"
        "        #     'downstream_component_ids': [...]\n"
        "        # }\n"
        "        rules: dict = {}\n"
        "        for ln in spec.get('logic_nodes', []):\n"
        "            rules[ln['id']] = {\n"
        "                'conditions': ln.get('conditions', []),\n"
        "                'downstream_component_ids': ln.get('downstream_component_ids', []),\n"
        "            }\n"
        "        return rules"
    )


# ---------------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------------

def _to_pythonIdentifier(s: str) -> str:
    """Convert any string to a valid Python identifier."""
    import re
    s = re.sub(r"[^a-zA-Z0-9_]", "_", s)
    s = re.sub(r"^[^a-zA-Z]+", "", s)
    return s or "_"


def _to_pythonFilename(s: str) -> str:
    """Convert system_id to a safe filename."""
    return _to_pythonIdentifier(s).lower()


# ---------------------------------------------------------------------------
# Templates (string constants)
# ---------------------------------------------------------------------------

_HEADER_COMMENT = '''"""
Auto-generated Python adapter — AI FANTUI LogicMVP P17-NLC-A
==============================================================
  system_id : {system_id}
  title     : {title}
  source    : {source_path}
  generated : {timestamp}

DO NOT EDIT THIS FILE DIRECTLY.
It was generated by: well_harness.tools.generate_adapter
Re-generate after editing the source spec JSON.
"""

# This file is part of AI FANTUI LogicMVP.
# https://github.com/kogamishinyajerry-ops/ai-fantui-logicmvp
'''

_THIRD_PARTY_IMPORT_BLOCK = '''from well_harness.controller_adapter import (
    ControllerTruthMetadata,
    GenericTruthEvaluation,
)'''

_METADATA_CLASS = '''@dataclass(frozen=True)
class ControllerTruthMetadata:
    adapter_id: str
    system_id: str
    truth_kind: str
    source_of_truth: str
    description: str

    def to_dict(self) -> dict:
        return {
            "$schema": "https://well-harness.local/json_schema/controller_truth_adapter_metadata_v1.schema.json",
            "kind": "well-harness-controller-truth-adapter-metadata",
            "version": 1,
            **vars(self),
        }'''

_GENERIC_TRUTH_EVAL_CLASS = '''@dataclass(frozen=True, eq=False)
class GenericTruthEvaluation:
    system_id: str
    active_logic_node_ids: tuple[str, ...]
    asserted_component_values: dict[str, Any]
    completion_reached: bool
    blocked_reasons: tuple[str, ...]
    summary: str

    def to_dict(self) -> dict:
        return {
            "system_id": self.system_id,
            "active_logic_node_ids": list(self.active_logic_node_ids),
            "asserted_component_values": dict(self.asserted_component_values),
            "completion_reached": self.completion_reached,
            "blocked_reasons": list(self.blocked_reasons),
            "summary": self.summary,
        }'''

_ADAPTER_CLASS_BEGIN = '''class {adapter_id}:
    """
    Spec-derived GenericControllerTruthAdapter.

    Implements GenericControllerTruthAdapter by evaluating the logic_nodes
    defined in the embedded spec dict directly against the incoming snapshot.

    This adapter is AUTO-GENERATED by tools/generate_adapter.py from a
    control_system_spec_v1 JSON document.  Do not edit by hand —
    re-run the code generator after updating the source spec.
    """

    def __init__(self, spec: dict[str, Any] | None = None) -> None:
        self.spec = spec or _load_spec_dict()
        self._logic_rules: dict = {{}}
        self._refresh_rules()

    def _refresh_rules(self) -> None:
        """Rebuild internal logic rules from the current spec."""
        self._logic_rules = {{
            ln["id"]: {{
                "conditions": ln.get("conditions", []),
                "downstream_component_ids": tuple(ln.get("downstream_component_ids", [])),
            }}
            for ln in self.spec.get("logic_nodes", [])
        }}
'''

_ADAPTER_CLASS_END = ""


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def _main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate a Python adapter from a control_system_spec_v1 JSON file.",
    )
    parser.add_argument(
        "spec",
        type=Path,
        help="Path to the control_system_spec_v1 JSON file",
    )
    parser.add_argument(
        "-o", "--output",
        type=Path,
        default=None,
        help="Output path (default: <system_id>_adapter.py next to spec)",
    )
    args = parser.parse_args()

    output = args.output
    if output is None:
        stem = args.spec.stem
        output = args.spec.parent / f"{stem}_adapter.py"

    write_adapter_from_spec(args.spec, output)


if __name__ == "__main__":
    _main()
