from __future__ import annotations

import copy
import json
import os
import sys
from pathlib import Path
from typing import Any


PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = PROJECT_ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from well_harness.workbench_changerequest_handoff import (  # type: ignore[import-untyped]
    CHANGE_REQUEST_HANDOFF_CANONICALIZATION,
    CHANGE_REQUEST_HANDOFF_KIND,
    CHANGE_REQUEST_HANDOFF_SCHEMA_ID,
    CHANGE_REQUEST_HANDOFF_SCHEMA_PATH,
    CHANGE_REQUEST_HANDOFF_VERSION,
    changerequest_handoff_hash,
    load_changerequest_handoff_schema,
    validate_changerequest_handoff_packet,
)


FORCE_JSONSCHEMA_MISSING_ENV = "WELL_HARNESS_FORCE_JSONSCHEMA_MISSING"
OUTPUT_FORMATS = {"text", "json"}
OPTIONAL_JSONSCHEMA_SKIP_MESSAGE = (
    "SKIP: optional dependency 'jsonschema' is not installed. "
    "Install it to validate workbench ChangeRequest handoff payloads."
)


def relative_path(path: Path) -> str:
    try:
        return path.relative_to(PROJECT_ROOT).as_posix()
    except ValueError:
        return path.as_posix()


def format_validation_error(error: Any) -> str:
    path = "$"
    for path_part in error.absolute_path:
        if isinstance(path_part, int):
            path += f"[{path_part}]"
        else:
            path += f".{path_part}"
    return f"{path}: {error.message}"


def sample_changerequest_handoff_packet() -> dict[str, Any]:
    proof_packet = {
        "kind": "well-harness-workbench-changerequest-proof-packet",
        "version": 1,
        "linear": {
            "issue": "JER-TBD",
            "project": "AI FANTUI LogicMVP · Editable Workbench v4 Authoring + Hardware Design",
            "live_mutation": False,
            "agent_eligible": "No",
        },
        "adapter": "thrust-reverser",
        "layer": "L4",
        "candidate_state": "sandbox_candidate",
        "certification_claim": "none",
        "truth_level_impact": "none",
        "dal_pssa_impact": "none",
        "red_lines_touched": "none",
        "controller_truth_modified": False,
        "frozen_assets_modified": False,
        "truth_effect": "none",
        "changed_model_hash": "ui_draft_11111111",
        "selected_scenario_id": "nominal_landing",
        "selected_node_id": "etrac_unlock_logic",
        "sandbox_diff": {
            "verdict": "not_run",
            "truth_level_impact": "none",
        },
    }
    return {
        "$schema": CHANGE_REQUEST_HANDOFF_SCHEMA_ID,
        "kind": CHANGE_REQUEST_HANDOFF_KIND,
        "version": CHANGE_REQUEST_HANDOFF_VERSION,
        "packet_state": "draft",
        "candidate_state": "sandbox_candidate",
        "certification_claim": "none",
        "truth_effect": "none",
        "live_linear_mutation": False,
        "controller_truth_modified": False,
        "frozen_assets_modified": False,
        "truth_level_impact": "none",
        "dal_pssa_impact": "none",
        "red_lines_touched": "none",
        "artifact_scope": "browser_local_draft",
        "truth_scope": "evidence_only",
        "runtime_mutates_truth": False,
        "serialization": {
            "canonicalization": CHANGE_REQUEST_HANDOFF_CANONICALIZATION,
            "checksum_algorithm": "ui_fnv1a32_over_canonical_json",
        },
        "outcome": "Review sandbox candidate edit against the certified thrust-reverser baseline.",
        "context": "Generated by /workbench from a sandbox candidate and local evidence archive.",
        "acceptance": [
            "Candidate draft hash is recorded.",
            "Baseline diff evidence is attached before implementation.",
        ],
        "boundaries": [
            "No live Linear mutation from the workbench.",
            "No controller.py truth semantics edit.",
        ],
        "evidence_required": [
            "Editable draft JSON export.",
            "Structured ChangeRequest proof packet.",
        ],
        "red_line_metadata": {
            "red_lines_touched": "none",
            "truth_level_impact": "none",
            "dal_pssa_impact": "none",
            "controller_truth_modified": False,
            "frozen_assets_modified": False,
            "live_linear_mutation": False,
        },
        "metadata": {
            "linear_issue": "JER-TBD",
            "linear_project": "AI FANTUI LogicMVP · Editable Workbench v4 Authoring + Hardware Design",
            "adapter": "thrust-reverser",
            "layer": "L4",
            "selected_scenario_id": "nominal_landing",
            "selected_node_id": "etrac_unlock_logic",
            "changed_model_hash": "ui_draft_11111111",
            "sandbox_verdict": "not_run",
            "diff_review_v2": {
                "verdict": "not_run",
                "truth_effect": "none",
            },
            "test_delta": {
                "targeted_pytest": "pending",
                "default_pytest": "pending",
                "gsd_validation_suite": "pending",
                "adversarial_8_8": "pending",
                "e2e_49_49": "not_claimed",
                "mypy_strict_clean": "not_claimed",
                "truth_effect": "none",
            },
            "agent_eligible": "No",
        },
        "artifacts": {
            "linear_issue_body_checksum": "ui_draft_22222222",
            "pr_proof_packet_checksum": "ui_draft_33333333",
            "changerequest_proof_packet_checksum": "ui_draft_44444444",
            "diff_review_v2_checksum": "not_available",
        },
        "linear_issue_body": "## Outcome\nReview sandbox candidate edit.",
        "pr_proof_packet": "Linear: JER-TBD\nTruth-level impact: none",
        "changerequest_proof_packet": proof_packet,
    }


def schema_negative_cases() -> tuple[dict[str, Any], ...]:
    cases: list[dict[str, Any]] = []

    live_linear = copy.deepcopy(sample_changerequest_handoff_packet())
    live_linear["live_linear_mutation"] = True
    live_linear["red_line_metadata"]["live_linear_mutation"] = True
    cases.append({"name": "live_linear_mutation_rejected", "payload": live_linear})

    certified_claim = copy.deepcopy(sample_changerequest_handoff_packet())
    certified_claim["certification_claim"] = "certified"
    certified_claim["changerequest_proof_packet"]["certification_claim"] = "certified"
    cases.append({"name": "certification_claim_rejected", "payload": certified_claim})

    truth_level = copy.deepcopy(sample_changerequest_handoff_packet())
    truth_level["truth_level_impact"] = "certified"
    truth_level["red_line_metadata"]["truth_level_impact"] = "certified"
    truth_level["changerequest_proof_packet"]["truth_level_impact"] = "certified"
    cases.append({"name": "truth_level_impact_rejected", "payload": truth_level})

    missing_field = copy.deepcopy(sample_changerequest_handoff_packet())
    del missing_field["evidence_required"]
    cases.append({"name": "missing_required_field_rejected", "payload": missing_field})

    return tuple(cases)


def make_report(status: str = "pass") -> dict[str, Any]:
    return {
        "canonicalization": CHANGE_REQUEST_HANDOFF_CANONICALIZATION,
        "hash_algorithm": "sha256",
        "results": [],
        "schema_path": relative_path(CHANGE_REQUEST_HANDOFF_SCHEMA_PATH),
        "schema": CHANGE_REQUEST_HANDOFF_SCHEMA_ID,
        "status": status,
    }


def validate_workbench_changerequest_handoff_payloads() -> tuple[int, dict[str, Any], list[str]]:
    report = make_report()

    if os.environ.get(FORCE_JSONSCHEMA_MISSING_ENV) == "1":
        report["reason"] = OPTIONAL_JSONSCHEMA_SKIP_MESSAGE
        report["status"] = "skip"
        return 0, report, [OPTIONAL_JSONSCHEMA_SKIP_MESSAGE]

    try:
        from jsonschema import Draft202012Validator  # type: ignore[import-untyped]
    except ImportError:
        report["reason"] = OPTIONAL_JSONSCHEMA_SKIP_MESSAGE
        report["status"] = "skip"
        return 0, report, [OPTIONAL_JSONSCHEMA_SKIP_MESSAGE]

    try:
        schema_document = load_changerequest_handoff_schema()
        Draft202012Validator.check_schema(schema_document)
    except Exception as exc:
        report["failure_kind"] = "schema_unavailable"
        report["reason"] = str(exc)
        report["status"] = "fail"
        return 1, report, [f"FAIL schema: unable to use {relative_path(CHANGE_REQUEST_HANDOFF_SCHEMA_PATH)}: {exc}"]

    validator = Draft202012Validator(schema_document)
    text_lines: list[str] = []

    valid_payload = sample_changerequest_handoff_packet()
    structural_issues = validate_changerequest_handoff_packet(valid_payload)
    errors = sorted(
        validator.iter_errors(valid_payload),
        key=lambda error: tuple(error.absolute_path),
    )
    if structural_issues or errors:
        formatted_errors = [*structural_issues, *(format_validation_error(error) for error in errors[:10])]
        report["failure_kind"] = "valid_payload_rejected"
        report["results"].append(
            {
                "case": "valid_handoff_packet",
                "validation_status": "fail",
                "error_count": len(formatted_errors),
                "errors": formatted_errors,
            }
        )
        report["status"] = "fail"
        return 1, report, [f"FAIL valid_handoff_packet: {'; '.join(formatted_errors)}"]

    scrambled_payload = copy.deepcopy(valid_payload)
    scrambled_payload = {
        "pr_proof_packet": scrambled_payload["pr_proof_packet"],
        "linear_issue_body": scrambled_payload["linear_issue_body"],
        **{key: value for key, value in scrambled_payload.items() if key not in {"pr_proof_packet", "linear_issue_body"}},
    }
    stable_hash = changerequest_handoff_hash(valid_payload)
    if changerequest_handoff_hash(scrambled_payload) != stable_hash:
        report["failure_kind"] = "stable_hash_order_drift"
        report["results"].append(
            {
                "case": "canonical_hash_order_invariance",
                "validation_status": "fail",
                "error_count": 1,
                "errors": ["equivalent payloads with different key order produced different hashes"],
            }
        )
        report["status"] = "fail"
        return 1, report, ["FAIL canonical_hash_order_invariance: equivalent key order drift changed hash"]

    report["results"].append(
        {
            "case": "valid_handoff_packet",
            "validation_status": "pass",
            "canonical_hash": stable_hash,
            "error_count": 0,
            "errors": [],
        }
    )
    report["results"].append(
        {
            "case": "canonical_hash_order_invariance",
            "validation_status": "pass",
            "canonical_hash": stable_hash,
            "error_count": 0,
            "errors": [],
        }
    )
    text_lines.append("OK valid_handoff_packet: schema, red-line constants, and canonical hash validated")
    text_lines.append("OK canonical_hash_order_invariance: stable hash survived top-level key reorder")

    for case in schema_negative_cases():
        payload = case["payload"]
        structural_issues = validate_changerequest_handoff_packet(payload)
        errors = sorted(
            validator.iter_errors(payload),
            key=lambda error: tuple(error.absolute_path),
        )
        if not structural_issues and not errors:
            report["failure_kind"] = "negative_case_accepted"
            report["results"].append(
                {
                    "case": case["name"],
                    "validation_status": "fail",
                    "error_count": 1,
                    "errors": ["invalid handoff packet was accepted"],
                }
            )
            report["status"] = "fail"
            return 1, report, [f"FAIL {case['name']}: invalid handoff packet was accepted"]
        issue_count = len(structural_issues) + len(errors)
        report["results"].append(
            {
                "case": case["name"],
                "validation_status": "pass",
                "error_count": issue_count,
                "errors": [*structural_issues, *(format_validation_error(error) for error in errors[:10])],
            }
        )
        text_lines.append(f"OK {case['name']}: rejected with {issue_count} validation issue(s)")

    text_lines.append(
        "PASS: validated ChangeRequest handoff packet schema and stable serialization contract "
        f"against {relative_path(CHANGE_REQUEST_HANDOFF_SCHEMA_PATH)}"
    )
    return 0, report, text_lines


def parse_output_format(argv: list[str]) -> str:
    if not argv:
        return "text"
    if len(argv) == 2 and argv[0] == "--format" and argv[1] in OUTPUT_FORMATS:
        return argv[1]
    raise ValueError("usage: validate_workbench_changerequest_handoff_schema.py [--format text|json]")


def emit_report(report: dict[str, Any], text_lines: list[str], output_format: str) -> None:
    if output_format == "json":
        print(json.dumps(report, indent=2, sort_keys=True))
        return
    for line in text_lines:
        print(line)


def main(argv: list[str] | None = None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)
    try:
        output_format = parse_output_format(argv)
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        return 2

    exit_code, report, text_lines = validate_workbench_changerequest_handoff_payloads()
    emit_report(report, text_lines, output_format)
    return exit_code


if __name__ == "__main__":
    raise SystemExit(main())
